name: mvctest
services:
  nginx:
    image: nginx:alpine
    volumes:
      - './etc/nginx:/etc/nginx/conf.d'
      - '../public:/var/www/public'
      - '../app:/var/www/app'
      - '../vendor:/var/www/vendor'
      - '../config:/var/www/config'
    ports:
      - '8080:80'
    restart: always
    depends_on:
      - php
      - db
      - mongo
      - rabbitmq
      - elasticsearch
  php:
    build: .
    restart: always
    volumes:
      - './etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - '../public:/var/www/public'
      - '../app:/var/www/app'
      - '../vendor:/var/www/vendor'
      - '../config:/var/www/config'
    depends_on:
      - db
      - mongo
      - rabbitmq
      - elasticsearch
  composer:
    image: composer
    volumes:
      - '../app:/app'
    command: install --ignore-platform-reqs
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mvctest
      - MYSQL_USER=mvctest
      - MYSQL_PASSWORD=mvctest
    ports:
      - '3306:3306'
    volumes:
      - './data/db/mysql:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: mvctest
      MONGO_INITDB_ROOT_PASSWORD: mvctest
    ports:
      - '27017:27017'
    volumes:
      - './data/db/mongo:/data/db'
  memcached:
    image: memcached:alpine
    restart: always
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=mvctest
      - RABBITMQ_DEFAULT_PASS=mvctest
    volumes:
      - './data/rabbitmq:/var/lib/rabbitmq'
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    restart: always